# =======================================#
# Imports                                #
# =======================================#
# Python Imports
import os

# Module Imports
from src.MarkovProb import *
from Data.preprocess import *

# =======================================#
# Globals & Constants                    #
# =======================================#

BEEF_JERKY_PRIOR = os.path.join(os.getcwd(), 'Data', 'orders_prior_beef_jerky.csv')
BEEF_JERKY_PRIOR_BOUGHT = os.path.join(os.getcwd(), 'Data', 'orders_prior_beef_jerky_bought.csv')
TRAIL_MIX_PRIOR = os.path.join(os.getcwd(), 'Data', 'orders_prior_trail_mix.csv')
TRAIL_MIX_PRIOR_BOUGHT = os.path.join(os.getcwd(), 'Data', 'orders_prior_trail_mix_bought.csv')
PROTEIN_BARS_PRIOR = os.path.join(os.getcwd(), 'Data', 'orders_prior_protein_bars.csv')
PROTEIN_BARS_PRIOR_BOUGHT = os.path.join(os.getcwd(), 'Data', 'orders_prior_protein_bars_bought.csv')
BEEF_JERKY_TEST = os.path.join(os.getcwd(), 'Data', 'orders_chain_beef_jerky.csv')
TRAIL_MIX_TEST = os.path.join(os.getcwd(), 'Data', 'orders_chain_trail_mix.csv')
PROTEIN_BARS_TEST = os.path.join(os.getcwd(), 'Data', 'orders_chain_protein_bars.csv')
CHAIN_CSV = os.path.join(os.getcwd(), 'Data', 'orders_chain.csv')
CHAIN_DICT = os.path.join(os.getcwd(), 'Data', 'order_chain.json')

# bj_data = parse_run_csv(BEEF_JERKY_PRIOR)
tm_data = parse_run_csv(TRAIL_MIX_PRIOR)
# pb_data = parse_run_csv(PROTEIN_BARS_PRIOR)
# bj_data_b = parse_run_csv(BEEF_JERKY_PRIOR_BOUGHT)
tm_data_b = parse_run_csv(TRAIL_MIX_PRIOR_BOUGHT)
# pb_data_b = parse_run_csv(PROTEIN_BARS_PRIOR_BOUGHT)
# bj_test = parse_run_csv(BEEF_JERKY_TEST)
tm_test = parse_run_csv(TRAIL_MIX_TEST)
# pb_test = parse_run_csv(PROTEIN_BARS_TEST)
print('ready')

states = ['true', 'false']
tranNames = [['tt', 'tf'], ['ft', 'ff']]

# bj_weights = twoStateWeights(bj_data, states)
# tm_weights = twoStateWeights(tm_data, states)
# pb_weights = twoStateWeights(pb_data, states)
# bj_weights_b = twoStateWeights(bj_data_b, states)
# tm_weights_b = twoStateWeights(tm_data_b, states)
# pb_weights_b = twoStateWeights(pb_data_b, states)
bj_weights = [['0.40','0.60'],['0.00','1.00']]
tm_weights = [['0.38','0.62'],['0.00','1.00']]
pb_weights = [['0.39','0.61'],['0.01','0.99']]
bj_weights_b = [['0.40','0.60'],['0.09','0.91']]
tm_weights_b = [['0.38','0.62'],['0.10','0.90']]
pb_weights_b = [['0.39','0.61'],['0.08','0.92']]
# print('1')

# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)
print('')
# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)
print('')
# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)
print('')
# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)
print('')
# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)
print('')
# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)
print('')
# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)
print('')
# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)
print('')
# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)
print('')
# guessDays(bj_data, states, tranNames, bj_weights)
guessDays(tm_data,states,tranNames,tm_weights)
# guessDays(pb_data,states,tranNames,pb_weights)
# guessDays(bj_test, states, tranNames, bj_weights)
guessDays(tm_test,states,tranNames,tm_weights)
# guessDays(pb_test,states,tranNames,pb_weights)
# guessDays(bj_data, states, tranNames, bj_weights_b)
guessDays(tm_data,states,tranNames,tm_weights_b)
# guessDays(pb_data,states,tranNames,pb_weights_b)
# guessDays(bj_test, states, tranNames, bj_weights_b)
guessDays(tm_test,states,tranNames,tm_weights_b)
# guessDays(pb_test,states,tranNames,pb_weights_b)